[package]
name = "tmtbook"
version = "0.1.0"
edition = "2024"
description = "A standalone book & wiki generator for Tomet"

[[bin]]
name = "tmtbook"
path = "src/main.rs"

[dependencies]
tmtbook-core = { path = "crates/core" }
tmtbook-serve = { path = "crates/serve" }

#[ Crates.io ]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
notify = "6.1.1"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
embedded-search = ["tmtbook-core/embedded-search"]
embedded-search-extended = ["tmtbook-core/embedded-search-extended"]

[workspace]
members = ["crates/core", "crates/serve"]
