[book]
title = "tmtbook docs"
lang = "en"
dest = "dist"

[build]
base = "/tomet-book"
kinds = ["*", "!config", "!index"]
routing = "id"                     # "hierarchical" (default) | "flat" | "id"

[ui.markers]
enable = true
strikethrough = true

[ui.markers.custom]
fire = { icon = "flame", color = "#f97316" }
