[net]
git-fetch-with-cli = true

[patch."https://github.com/tomet-lang/tomet.git"]
tomet-ast       = { path = "../tomet/crates/tomet-syntax-ast" }
tomet-parser    = { path = "../tomet/crates/tomet-syntax-parser" }
tomet-tree      = { path = "../tomet/crates/tomet-syntax-tree" }
tomet-semantics = { path = "../tomet/crates/tomet-semantics" }
tomet-transform = { path = "../tomet/crates/tomet-transform" }
tomet-links     = { path = "../tomet/crates/tomet-workspace-links" }
tomet-html      = { path = "../tomet/crates/tomet-convert-html" }
tomet-load      = { path = "../tomet/crates/tomet-load" }

[patch."https://github.com/tomet-lang/tomet.git"]
tomet-ast       = { path = "../tomet/crates/tomet-syntax-ast" }
tomet-parser    = { path = "../tomet/crates/tomet-syntax-parser" }
tomet-tree      = { path = "../tomet/crates/tomet-syntax-tree" }
tomet-semantics = { path = "../tomet/crates/tomet-semantics" }
tomet-transform = { path = "../tomet/crates/tomet-transform" }
tomet-links     = { path = "../tomet/crates/tomet-workspace-links" }
tomet-html      = { path = "../tomet/crates/tomet-convert-html" }
tomet-load      = { path = "../tomet/crates/tomet-load" }
